iptables:
  public_tcp_ports:
    - 22
    - 80

mosquitto:
  allow_connections_from:
    - your.ip.address.here

postgresql:
  databases:
    - name: loraserver
      user: loraserver
      password: verysecret

lora_gateway_bridge:
  allow_connections_from:
    - your.ip.address.here

loraserver:
  configuration:
    BAND: EU_863_870
    NET_ID: "010203"

lora_app_server:
  allow_connections_from:
    - your.ip.address.here
  tls_certificate:
    domain: example.com
    email: info@example.com
    # Set accept_letsencrypt_tos to True if you accept the LE terms of service
    # and to request a free TLS certificate, see https://letsencrypt.org
    accept_letsencrypt_tos: False
  configuration:
    POSTGRES_DSN: postgres://loraserver:verysecret@localhost/loraserver?sslmode=disable
    HTTP_BIND: 0.0.0.0:443
