# iptable configuration
#
# all ports will be blocked, except the ports listed below
iptables:
  accept:
    -
      port: 22
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 80
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 443
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 1883
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 1884
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 8083
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 8883
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 1700
      source: 0.0.0.0/0
      protocol: udp

# mosquitto configuration (MQTT)
#
# this defines the listeners (and protocols) and the usernames that
# are allowed to connect to the MQTT broker and to which MQTT topics
# they are restricted
mosquitto:
  # the full domain by which the MQTT broker is reachable
  # e.g. subdomain.example.com
  fqdn: subdomain.example.com
  letsencrypt:
    email: info@example.com
    request: False
  users:
    -
      user: loraserver_gw
      password: loraserver_gw
      topics:
        - write gateway/+/event/+
        - read gateway/+/command/+
    -
      user: loraserver_ns
      password: loraserver_ns
      topics:
        - read gateway/+/event/+
        - write gateway/+/command/+
    -
      user: loraserver_as
      password: loraserver_as
      topics:
          - write application/+/device/+/rx
          - write application/+/device/+/join
          - write application/+/device/+/ack
          - write application/+/device/+/error
          - write application/+/device/+/status
          - write application/+/device/+/location
          - read application/+/device/+/tx
    -
      user: loraserver_app
      password: loraserver_app
      topics:
        - write application/+/device/+/tx
        - read application/+/device/+/rx
        - read application/+/device/+/join
        - read application/+/device/+/ack
        - read application/+/device/+/error
        - read application/+/device/+/status
        - read application/+/device/+/location

# postgresql configuration
#
# this defines the databases that will be created and the credentials to
# connect to these databases
postgresql:
  databases:
    -
      name: loraserver_as
      user: loraserver_as
      password: loraserver_as
    -
      name: loraserver_ns
      user: loraserver_ns
      password: loraserver_ns

# lora-app-server configuration
lora_app_server:
  # the full domain by which LoRa App Server is reachable
  # e.g. subdomain.example.com
  fqdn: localhost
  letsencrypt:
    email: info@example.com
    request: False

