- name: install packages
  ansible.builtin.package: 
    name:
      - python3-psycopg2
      - python-psycopg2
      - python3-psycopg2
      - postgresql
    state: latest

- name: start postgresql on boot
  service:
    name: postgresql
    state: started
    enabled: yes

- name: create databases
  include_tasks: create_db.yml
  with_items: "{{ postgresql.databases }}"
