- name: add postgresql gpg key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: add postgresql deb repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main

- name: install packages
  package: name={{ item }} state=latest
  with_items:
    - python-psycopg2
    - postgresql-9.6

- name: start postgresql on boot
  service: name=postgresql state=started enabled=yes

- name: create roles
  postgresql_user: name={{ item.user}} password={{ item.password }} role_attr_flags=LOGIN
  become_user: postgres
  with_items: '{{ postgresql.databases }}'
  no_log: true

- name: create databases
  postgresql_db: name={{ item.name }} owner={{ item.user }}
  become_user: postgres
  with_items: '{{ postgresql.databases }}'
  no_log: true
