- name: generate password
  command: /opt/mosquitto-auth-plug/np -i 100000 -p {{ item.password }}
  register: password

- name: add password to file
  lineinfile:
    path: /etc/mosquitto/mosquitto-auth-plug/passwords
    regexp: '^{{ item.user }}:'
    line: '{{ item.user }}:{{ password.stdout }}'
  notify:
    - restart mosquitto
