# See https://www.loraserver.io/lora-gateway-bridge/install/config/ for a full
# configuration example and documentation.

[backend.mqtt]
server="tcp://127.0.0.1:1883"
username="loraserver_gw"
password="loraserver_gw"
