- name: allow connections on configured ports
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    source: "{{ item.source }}"
  with_items: "{{ iptables.accept }}"

- name: allow established connections
  iptables: chain=INPUT ctstate=ESTABLISHED,RELATED jump=ACCEPT

- name: allow loopback input
  iptables: chain=INPUT in_interface=lo jump=ACCEPT

- name: allow loopback output
  iptables: chain=OUTPUT out_interface=lo jump=ACCEPT

- name: drop all other connections
  command: iptables -P INPUT DROP

- name: persist iptables roles
  shell: iptables-save > /etc/iptables/rules.v4
