# See https://www.chirpstack.io/network-server/install/config/ for a full
# configuration example and documentation.
#
# This file is for the EU868 band. See the examples/ folder for more
# configuration examples.

[postgresql]
dsn="postgres://chirpstack_ns:chirpstack_ns@localhost/chirpstack_ns?sslmode=disable"

[network_server]
net_id="000000"

[network_server.band]
name="{{ chirpstack_network_server_band }}"

[network_server.network_settings]

{{ chirpstack_network_server_extra_channels }}

[network_server.gateway.backend.mqtt]
server="tcp://localhost:1883"
username="chirpstack_ns"
password="chirpstack_ns"

[geolocation_server]
server="localhost:8005"
