# Ansible managed

[postgresql]
dsn="postgres://chirpstack_ns:{{ chirpstack_network_server_postgres_pwd | urlencode }}@localhost/chirpstack_ns?sslmode=disable"

[network_server]
net_id="000000"

[network_server.band]
name="{{ chirpstack_network_server_band }}"

[network_server.network_settings]

{{ chirpstack_network_server_extra_channels }}

[network_server.gateway.backend.mqtt]
server="tcp://localhost:1883"
username="chirpstack_ns"
password="{{ chirpstack_network_server_mosquitto_pwd }}"

[geolocation_server]
server="localhost:8005"
