- name: install lora-gateway-bridge
  package: name=lora-gateway-bridge state=latest

- name: apply settings
  lineinfile:
    dest: /etc/default/lora-gateway-bridge
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ lora_gateway_bridge.configuration | default({}) }}"
  notify:
    - restart lora-gateway-bridge

- name: start lora-gateway-bridge on boot
  service: name=lora-gateway-bridge state=started enabled=yes

- name: allow connections from configured ip addresses to port 1700 (UDP)
  iptables: chain=INPUT protocol=udp source={{ item }} destination_port=1700 jump=ACCEPT
  with_items: '{{ lora_gateway_bridge.allow_connections_from }}'

- name: save iptables roles
  shell: iptables-save > /etc/iptables/rules.v4
