- name: install lora-gateway-bridge
  package:
    name: lora-gateway-bridge
    state: latest

- name: copy configuration
  template:
    src: lora-gateway-bridge.toml
    dest: /etc/lora-gateway-bridge/lora-gateway-bridge.toml
    owner: gatewaybridge
    group: gatewaybridge
    mode: 0640
  notify:
    - restart lora-gateway-bridge

- name: start lora-gateway-bridge on boot
  service:
    name: lora-gateway-bridge
    state: started
    enabled: yes
