- name: install lora-app-server
  package: name=lora-app-server state=latest

- name: copy configuration
  template:
    src: lora-app-server.toml
    dest: /etc/lora-app-server/lora-app-server.toml
    owner: appserver
    group: appserver
    mode: 0640
  notify:
    - restart lora-app-server

- name: request letsencrypt certificate
  command: certbot --nginx certonly --non-interactive --agree-tos -m {{ lora_app_server.letsencrypt.email }} -d {{ lora_app_server.fqdn }}
  when: lora_app_server.letsencrypt.accept_letsencrypt_tos

- name: add nginx proxy
  template:
    src: lora-app-server.nginx
    dest: /etc/nginx/sites-enabled/lora-app-server
  notify:
    - reload nginx

- name: start lora-app-server on boot
  service: name=lora-app-server state=started enabled=yes

