- name: install lora-app-server
  package: name=lora-app-server state=latest

- name: allow lora-app-server to bind to port 443
  capabilities: path=/usr/bin/lora-app-server capability=cap_net_bind_service+ep state=present

- name: apply settings
  lineinfile:
    dest: /etc/default/lora-app-server
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ lora_app_server.configuration | default({}) }}"
  no_log: true
  notify:
    - restart lora-app-server

- name: request letsencrypt certificate
  command: certbot certonly --standalone --standalone-supported-challenges http-01 --non-interactive --agree-tos -m {{ lora_app_server.tls_certificate.email }} -d {{ lora_app_server.tls_certificate.domain }} creates=/etc/letsencrypt/live/{{ lora_app_server.tls_certificate.domain }}
  when: lora_app_server.tls_certificate.accept_letsencrypt_tos

- name: copy certificate files
  copy: src=/etc/letsencrypt/live/{{ lora_app_server.tls_certificate.domain }}/{{ item.src }} dest=/etc/lora-app-server/certs/{{ item.dest }} remote_src=true follow=true owner=appserver group=appserver mode=0640
  with_items:
    - {src: 'fullchain.pem', dest: 'http.pem'}
    - {src: 'privkey.pem', dest: 'http-key.pem'}
  when: lora_app_server.tls_certificate.accept_letsencrypt_tos
  notify:
    - restart lora-app-server  

- name: start lora-app-server on boot
  service: name=lora-app-server state=started enabled=yes

- name: allow connections from configured ip addresses to port 443
  iptables: chain=INPUT protocol=tcp source={{ item }} destination_port=443 jump=ACCEPT
  with_items: '{{ lora_app_server.allow_connections_from }}'

- name: save iptables roles
  shell: iptables-save > /etc/iptables/rules.v4
