- name: install loraserver
  package:
    name: loraserver
    state: latest

- name: copy configuration
  template:
    src: loraserver.toml
    dest: /etc/loraserver/loraserver.toml
    owner: loraserver
    group: loraserver
    mode: 0640
  notify:
    - restart loraserver

- name: start loraserver on boot
  service:
    name: loraserver
    state: started
    enabled: yes
