- name: install loraserver
  package: name=loraserver state=latest

- name: apply settings
  lineinfile:
    dest: /etc/default/loraserver
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ loraserver.configuration | default({}) }}"
  notify:
    - restart loraserver

- name: start loraserver on boot
  service: name=loraserver state=started enabled=yes
