- name: add mosquitto repo (debian jessie)
  include: debian_jessie.yml
  when: ansible_distribution == 'Debian'

- name: add mosquitto ppa (ubuntu trusty)
  include: ubuntu_ppa.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: install packages
  package: name={{ item }} state=latest
  with_items:
    - mosquitto
    - mosquitto-clients

- name: copy mosquitto configuration
  template: src=listeners.conf dest=/etc/mosquitto/conf.d/listeners.conf
  notify:
    - restart mosquitto

- name: start mosquitto on boot
  service: name=mosquitto state=started enabled=yes

- name: allow connections from configured ip addresses
  iptables: chain=INPUT protocol=tcp source={{ item[0] }} destination_port={{ item[1].bind_port }} jump=ACCEPT
  with_nested:
    - '{{ mosquitto.allow_connections_from }}'
    - '{{ mosquitto.listeners }}'

- name: save iptables roles
  shell: iptables-save > /etc/iptables/rules.v4
