- name: install packages
  package: name={{ item }} state=latest
  with_items:
    - mosquitto
    - mosquitto-clients

- name: copy mosquitto configuration
  template: src=listeners.conf dest=/etc/mosquitto/conf.d/listeners.conf
  notify:
    - restart mosquitto

- name: start mosquitto on boot
  service: name=mosquitto state=started enabled=yes
