- name: install packages
  ansible.builtin.package:
    name:
      - mosquitto
      - mosquitto-clients
    state: latest

- name: copy mosquitto configuration
  template: 
    src: listeners.conf
    dest: /etc/mosquitto/conf.d/listeners.conf
    mode: '666'
  notify:
    - restart mosquitto

- name: request letsencrypt certificate
  command: certbot --nginx certonly --non-interactive --agree-tos -m {{ mosquitto.letsencrypt.email }} -d {{ mosquitto.fqdn }}
  when: mosquitto.letsencrypt.request

- name: start mosquitto on boot
  service:
    name: mosquitto
    state: started
    enabled: yes
