- name: add mosquitto PPA repository
  apt_repository:
    repo: ppa:mosquitto-dev/mosquitto-ppa
  when: ansible_distribution == 'Ubuntu'

- name: add mosquitto gpg key
  apt_key:
    url: http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
  when: ansible_distribution == 'Debian'

- name: add mosquitto deb repository
  apt_repository:
    repo: deb http://repo.mosquitto.org/debian jessie main
  when: ansible_distribution == 'Debian'

- name: install mosquitto
  package: name=mosquitto state=latest

- name: copy mosquitto configuration
  template: src=listeners.conf dest=/etc/mosquitto/conf.d/listeners.conf
  notify:
    - restart mosquitto

- name: start mosquitto on boot
  service: name=mosquitto state=started enabled=yes

- name: allow connections from configured ip addresses
  iptables: chain=INPUT protocol=tcp source={{ item[0] }} destination_port={{ item[1].bind_port }} jump=ACCEPT
  with_nested:
    - '{{ mosquitto.allow_connections_from }}'
    - '{{ mosquitto.listeners }}'

- name: save iptables roles
  shell: iptables-save > /etc/iptables/rules.v4
