iptables:
  public_tcp_ports:
    - 22

mosquitto:
  allow_connections_from:
    - 0.0.0.0/0
  listeners:
    -
      bind_address: 0.0.0.0
      bind_port: 1883
      protocol: mqtt
    -
      bind_address: 0.0.0.0
      bind_port: 1884
      protocol: websockets

postgresql:
  databases:
    - name: loraserver
      user: loraserver
      password: verysecret

lora_gateway_bridge:
  allow_connections_from:
    - 0.0.0.0/0

loraserver:
  configuration:
    BAND: EU_863_870
    NET_ID: "010203"

lora_app_server:
  allow_connections_from:
    - 0.0.0.0/0
  tls_certificate:
    accept_letsencrypt_tos: False
  configuration:
    POSTGRES_DSN: postgres://loraserver:verysecret@localhost/loraserver?sslmode=disable
    HTTP_BIND: 0.0.0.0:443
    JWT_SECRET: Y301pq2kbuKbZHHlrGCsIoiMf7UJAnlEerv8OHYD93Q=
