iptables:
  public_tcp_ports:
    - 22
    - 8002

mosquitto:
  allow_connections_from:
    - 0.0.0.0/0
  mosquitto_auth_plug:
    lora_app_server_integration: True
    db:
      host: localhost
      port: 5432
      dbname: loraserver_as
      user: loraserver_as
      pass: loraserver_as
    users:
      -
        user: loraserver_gw
        password: loraserver_gw
        topics:
          - write gateway/+/stats
          - write gateway/+/rx
          - read gateway/+/tx
      -
        user: loraserver_ns
        password: loraserver_ns
        topics:
          - read gateway/+/stats
          - write gateway/+/tx
          - read gateway/+/rx
      -
        user: loraserver_as
        password: loraserver_as
        topics:
          - write application/+/node/+/rx
          - write application/+/node/+/join
          - write application/+/node/+/ack
          - write application/+/node/+/error
          - read application/+/node/+/tx
  listeners:
    -
      bind_address: 0.0.0.0
      bind_port: 1883
      protocol: mqtt
    -
      bind_address: 0.0.0.0
      bind_port: 1884
      protocol: websockets

postgresql:
  databases:
    - name: loraserver_as
      user: loraserver_as
      password: loraserver_as
    - name: loraserver_ns
      user: loraserver_ns
      password: loraserver_ns

lora_gateway_bridge:
  allow_connections_from:
    - 0.0.0.0/0

lora_app_server:
  allow_connections_from:
    - 0.0.0.0/0
  tls_certificate:
    accept_letsencrypt_tos: False
