iptables:
  public_tcp_ports:
    - 22

mosquitto:
  allow_connections_from:
    - 0.0.0.0/0
  listeners:
    -
      bind_address: 0.0.0.0
      bind_port: 1883
      protocol: mqtt
    -
      bind_address: 0.0.0.0
      bind_port: 1884
      protocol: websockets

postgresql:
  # Don't forget to update the POSTGRES_DSN for each service!
  databases:
    - name: loraserver_as
      user: loraserver_as
      password: loraserver_as
    - name: loraserver_ns
      user: loraserver_ns
      password: loraserver_ns

lora_gateway_bridge:
  allow_connections_from:
    - 0.0.0.0/0

loraserver:
  configuration:
    BAND: EU_863_870
    NET_ID: "010203"
    POSTGRES_DSN: postgres://loraserver_ns:loraserver_ns@localhost/loraserver_ns?sslmode=disable

lora_app_server:
  allow_connections_from:
    - 0.0.0.0/0
  tls_certificate:
    accept_letsencrypt_tos: False
  configuration:
    POSTGRES_DSN: postgres://loraserver_as:loraserver_as@localhost/loraserver_as?sslmode=disable
    HTTP_BIND: 0.0.0.0:443
    JWT_SECRET: Y301pq2kbuKbZHHlrGCsIoiMf7UJAnlEerv8OHYD93Q=
