- name: update apt cache
  apt: update_cache=yes

- name: upgrade installed packages
  apt: upgrade=yes

- name: install packages
  package: name={{ item }} state=latest
  with_items:
    - iptables-persistent

- name: allow incoming connections on public exposed ports
  iptables: chain=INPUT protocol=tcp destination_port={{ item }} jump=ACCEPT
  with_items: '{{ iptables.public_tcp_ports }}'

- name: allow established connections
  iptables: chain=INPUT ctstate=ESTABLISHED,RELATED jump=ACCEPT

- name: allow loopback input
  iptables: chain=INPUT in_interface=lo jump=ACCEPT

- name: allow loopback output
  iptables: chain=OUTPUT out_interface=lo jump=ACCEPT

- name: drop all other connections
  command: iptables -P INPUT DROP

- name: save iptables roles
  shell: iptables-save > /etc/iptables/rules.v4
