# raw is used as not all targets have aptitude installed
- name: update apt cache
  raw: apt-get update

# raw is used as not all targets have aptitude installed
- name: upgrade installed packages
  raw: apt-get upgrade -y

- name: install packages
  package: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - iptables-persistent

- name: allow incoming connections on public exposed ports
  iptables: chain=INPUT protocol=tcp destination_port={{ item }} jump=ACCEPT
  with_items: '{{ iptables.public_tcp_ports }}'

- name: allow established connections
  iptables: chain=INPUT ctstate=ESTABLISHED,RELATED jump=ACCEPT

- name: allow loopback input
  iptables: chain=INPUT in_interface=lo jump=ACCEPT

- name: allow loopback output
  iptables: chain=OUTPUT out_interface=lo jump=ACCEPT

- name: drop all other connections
  command: iptables -P INPUT DROP

- name: persist iptables roles
  shell: iptables-save > /etc/iptables/rules.v4

- name: add gpg public key to validate LoRa Server package signatures
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 1CE2AFD36DBCCA00

- name: add LoRa Server deb repository
  apt_repository:
    repo: deb https://repos.loraserver.io/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} testing
