# not installing this rases the following issue on Debian Jessie:
# https://github.com/brocaar/loraserver-setup/issues/13
- name: install pip
  package: name=python-pip state=latest

- name: install recent version of PyOpenSSL
  pip:
    name: PyOpenSSL

- name: add jessie-backports backports repository
  apt_repository:
    repo: deb http://ftp.debian.org/debian jessie-backports main

- name: install certbot from backports
  apt:
    name: certbot
    state: latest
    default_release: jessie-backports
