- name: add stretch-backports repository
  apt_repository:
    repo: deb http://ftp.debian.org/debian stretch-backports main

- name: install certbot from backports
  apt:
    name: certbot
    state: latest
    default_release: stretch-backports
