- name: ubuntu install
  include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: debian install
  include: debian.yml
  when: ansible_distribution == 'Debian'

- name: setup renew cron
  cron: name="letsencrypt renew" minute="0" hour="0" job="certbot renew > /dev/null"
